[package]
name = "uniffi-bindgen-cs"
version = "1.0.2"
edition = "2018"

[[bin]]
name = "uniffi-bindgen-cs"
path = "src/main.rs"

[lib]
name = "uniffi_fixtures"
path = "src/uniffi_fixtures.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1"
askama = { version = "0.11", default-features = false, features = ["config"] }
clap = { version = "3.1", features = ["std", "derive"] }
extend = "1.1"
heck = "0.4"
uniffi_bindgen = { path = "3rd-party/uniffi-rs/uniffi_bindgen" }
serde = "1"
toml = "0.5"
camino = "1.0.8"
fs-err = "2.7.0"
paste = "1.0"
serde_json = "1.0.0"

uniffi-cs-disposable-fixture = { path = "fixtures/disposable", optional = true }
uniffi-example-arithmetic = { path = "3rd-party/uniffi-rs/examples/arithmetic", optional = true }
uniffi-example-callbacks = { path = "3rd-party/uniffi-rs/examples/callbacks", optional = true }
uniffi-example-custom-types = { path = "3rd-party/uniffi-rs/examples/custom-types", optional = true }
uniffi-example-geometry = { path = "3rd-party/uniffi-rs/examples/geometry/", optional = true }
uniffi-example-rondpoint = { path = "3rd-party/uniffi-rs/examples/rondpoint", optional = true }
uniffi-example-sprites = { path = "3rd-party/uniffi-rs/examples/sprites", optional = true }
uniffi-example-todolist = { path = "3rd-party/uniffi-rs/examples/todolist", optional = true }
uniffi-fixture-coverall = { path = "3rd-party/uniffi-rs/fixtures/coverall", optional = true }
uniffi-fixture-external-types = { path = "3rd-party/uniffi-rs/fixtures/external-types/lib", optional = true }
uniffi-fixture-time = { path = "3rd-party/uniffi-rs/fixtures/uniffi-fixture-time", optional = true }

[features]
uniffi_fixtures = [
    "uniffi-cs-disposable-fixture",
    "uniffi-example-arithmetic",
    "uniffi-example-callbacks",
    "uniffi-example-custom-types",
    "uniffi-example-geometry",
    "uniffi-example-rondpoint",
    "uniffi-example-sprites",
    "uniffi-example-todolist",
    "uniffi-fixture-coverall",
    "uniffi-fixture-external-types",
    "uniffi-fixture-time",
]
